### ISSUE TITLE
Suggestion: Option to disable particles or/and animations on hammers/sieves

### ISSUE THREAD

**Issue by Nagapito** [blay09/ExCompressum#105]
Might not seem much but 1.7.10 has that "awesome" performance and when you have a couple of machines on same space with particles and animations, it kinda affects the FPS a little.  

Would be nice if we could disable this animations and effects.

**Comment by blay09** [comment]
Animations do not affect FPS any more than static TESR models, that's why they are TESRs. I'm not sure how Minecraft's particle settings work, but does it not affect the amount of particles spawned / shown by the sieves?

Also are you sure it's Ex Compressum things and not some other blocks (Ex Astris, Ex Nihilo, Storage Drawers) that are causing the FPS lag? Check your chunk updates on F3. The mods I mentioned love unnecessarily causing the whole chunk to rerender.

**Comment by Nagapito** [comment]
I always had the impression that particles would have a negative affect on FPS performance and 1.7.10 being shitty as it is with a couple blocks causing FPS drops from 150 to 60... that these particles would also affect performance.  But, if you say they have no effect, I take your word.

**Comment by blay09** [comment]
That is not what I said, I'm saying you should be able to use Minecraft's Particle Settings to tone them down. But your issue is most likely still caused by something else.

**Comment by Nagapito** [comment]
I dont have an issue. Its just something I remembered when I looked at my 10 sieves and particles flying everywhere and I thought that all these particles might not be so awesome on a crappy machine and they are just cosmetic particles.

Also, lowering particles in options is a little extreme since not all particles are cosmetic and preventing particles from other mods to avoid FPS issues caused by cosmetic particles does not seem a good design. 

But again, this is just something I thought that could be an issue, so the suggestion... I am not saying it is an issue...

**Comment by timakro** [comment]
I experience a lot of lag from auto hammers caused by the rendering of the hammer and the hammered block and from auto sieves caused by the rendering of the sieve and the skin. I wrote down the fps I was getting while looking at said blocks. I filled a 10x10 area with each of the following 7 blocks and teleported to a fixed position before looking at the fps.

| Test | Block ID | Block Entity |
| --- | --- | --- |
| Furnace | `minecraft:furnace` | Not modified |
| Auto Hammer | `excompressum:auto_hammer` | Not modified |
| Auto Hammer with Block | `excompressum:auto_hammer` | `{CurrentStack:{id:"minecraft:cobblestone"}}` |
| Auto Compressed Hammer | `excompressum:auto_compressed_hammer` | Not modified |
| Auto Compressed Hammer with Block | `excompressum:auto_compressed_hammer` | `{CurrentStack:{id:"extrautils2:CompressedCobblestone"}}` |
| Auto Sieve | `excompressum:auto_sieve` | Not modified |
| Auto Heavy Sieve | `excompressum:auto_heavy_sieve` | Not modified |

Here are my results:

| Test | Fps | Screenshot |
| --- | --- | --- |
| Furnace | 163 | <img src="https://cloud.githubusercontent.com/assets/8438790/23331840/46b9c9c0-fb6e-11e6-93fc-37bad58aeaef.png" height="100"> |
| Auto Hammer | 77 | <img src="https://cloud.githubusercontent.com/assets/8438790/23331868/d7f930ba-fb6e-11e6-8997-0e0f975bc50d.png" height="100"> |
| Auto Hammer with Block | 23 | <img src="https://cloud.githubusercontent.com/assets/8438790/23331869/dba11ca0-fb6e-11e6-8efa-50ecfaff0b07.png" height="100"> |
| Auto Compressed Hammer | 86 | <img src="https://cloud.githubusercontent.com/assets/8438790/23331870/df969f1a-fb6e-11e6-89a3-5628a5528641.png" height="100"> |
| Auto Compressed Hammer with Block | 25 | <img src="https://cloud.githubusercontent.com/assets/8438790/23331872/e19a0018-fb6e-11e6-8e58-18f763202e6c.png" height="100"> |
| Auto Sieve | 8 | <img src="https://cloud.githubusercontent.com/assets/8438790/23331874/e4734a74-fb6e-11e6-9df3-7c2200a7165a.png" height="100"> |
| Auto Heavy Sieve | 9 | <img src="https://cloud.githubusercontent.com/assets/8438790/23331875/e60a894c-fb6e-11e6-96a1-858226465048.png" height="100"> |

Based on those results I suggest adding an option to disable the rendering of the hammer, hammered block, sieve (also sieved block) and skin.

**Comment by blay09** [comment]
Furnaces are rendered statically into the chunk, whereas the hammer/skin parts of the machines are rendered every frame, so they're not comparable with each other. Also when doing benchmarks you should disable other mods that may affect the outcome (Botania Garden of Glass Sky, Minimap, ...).

By filling an 11x11 area with machines you end up with 121 of them. FPS issues for such large amounts is not surprising, try spawning that amount of mobs & items and observe your FPS while looking at them.

Disabling their rendering is not a solution, rather you should build in normal scales (or live with the consequences and deal with them in other ways, such as moving them to a chunkloaded area out of view).

**Comment by timakro** [comment]
Right my tests where with 11x11 not 10x10 blocks, I messed that up. Now corrected in my previous post.

I have about a third of that amount in my survival world. Its really hard and tedious to extend the setup (placing blocks, configuring pipes, etc.) with the low fps I'm getting there. Functionality wise those machines have a similar complexity to furnaces or sag mills but they cause disproportionate amounts of lag in comparison to machines of various other mods I know. I see that the inner life of those blocks looks really cool but there should be at least an option to turn it off considering its only and only for aesthetics.

**Comment by Lirrec** [comment]
I just experienced similar large performance drops on MC 1.10.2 ( Ex Compressum 2.0.87 ).
I built some automated sieves and hammerers ( 20 each ) and noticed a severe performance drop.
A quick comparison showed that without the ~40 blocks placed i had ~180fps, with them i'm down to 48.

40 machines for something that is _intended_ for automation should not affect performance that much.
Especially in some larger modpacks and/or worlds/builds i'd gladly accept the simpler appearance of a static block for a rendering performance increase that is probably a magnitude or more in this case. I know they are really fancy and nice to look at right now, but for using them in automated setups, that's the least thing i ( and that is of course my personal opinion) care about. Some config option for a simpler and less performance heavy presentation of those machines would be really nice.

I really like your mod and would really enjoy being able to use those machines in larger setups without such a performance impact.
