### ISSUE TITLE
Ticking memory connection upon compressed mob death

### ISSUE THREAD

**Issue by Gunner76th** [blay09/ExCompressum#143]
I am playing the 1.7.10 release of Crash Landing HQM. Every time I kill a compressed zombie, the game crashes back to the launcher with the following crash: http://pastebin.com/b0scbYHx  I have already updated Ex Compressum to the most recent release for 1.7.10, and the crash still occurs. 

I have also cross posted this on your issue tracker on Curse: https://minecraft.curseforge.com/projects/ex-compressum/issues/5

**Comment by Gunner76th** [comment]
As a test thinking it was the fact I was using a tinkers tool to kill them with, I killed one with a piece of cobble, and still crashed http://pastebin.com/xDKjZzLf

I have also removed zombies from the compressed spawn list, in the hopes that it will at least prevent this from happening due to the compressed mobs.

**Comment by Gunner76th** [comment]
After encountering a compressed Creeper, it would appear that this issue is affecting ALL compressed mobs.

**Comment by blay09** [comment]
Looks like some compatibility issue, might be a coremod or something replacing the vanilla entities and not implementing the .getEntityData() method correctly. I suggest just disabling them in the config since this seems to be an isolated case and I'd rather not dig up my 1.7.10 workspace to "fix" it at this point.
