### ISSUE TITLE
Config option for clicks per second

### ISSUE THREAD

**Issue by Thedrummonger** [blay09/ExCompressum#166]
Would it be possible to get a config option for clicks per second? I completely understand why it was changed but I personally liked the insanely fast sieving with an autoclicker and I'm sure others did to. Just a suggestion though, not a huge deal.

**Comment by blay09** [comment]
It wasn't really changed, it's just that the system that was already there broke in the port to 1.10.2 and was fixed in the latest update. I don't really care much about restricting it, it was added mostly to discourage people from spam-clicking on servers. Might make it an option when I work on the next update.
