### ISSUE TITLE
Auto-Sieve no longer gets power from Mekanism cables in latest update

### ISSUE THREAD

**Issue by FnordMan** [blay09/ExCompressum#177]
Just upgraded to 2.0.76 from 2.0.68
in 2.0.68 the auto-sieve got power from Mekanism universal cables just fine, now in 2.0.76 it doesn't.

**Comment by blay09** [comment]
Mekanism needs to support Forge's energy capability. They're still on an outdated unofficial CoFH API, which was starting to cause issues now, which is why RF support was completely dropped in the latest version of Ex Compressum. 

Every up-to-date mod has either already updated to support Forge's energy capability or went with their own way of energy. There may still be power cables that support both CoFH RF as well as Forge's energy capability, so I suggest you use that to connect the machines.

**Comment by FnordMan** [comment]
Ok, wasn't aware that Mek still used the old RF api, just kind of assumed they had moved on, raised an issue over there.

**Comment by KingLemming** [comment]
Just to point something out - RF is updated and modernized, you may want to revisit this decision. :P 

It's trivial for RF-based mods to support FE, as it's largely just passthrough. Also, interfaces still offer performance benefits over capabilities. Thermal Expansion supports both, with RF having first priority on the "if" check due to the higher performance.
