### ISSUE TITLE
How to set up workspace for development?

### ISSUE THREAD

**Issue by JamesTompkins** [blay09/ExCompressum#237]
I have tried running setupDecompWorkspace and eclipse but it does not create an eclipse folder. I have tried replacing the gradlew file with a new one and running the same commands but the project doesn't run with an error related to extra utils. Is this due to the new gradlew file?

**Comment by blay09** [comment]
Extra Utilities doesn't run well in dev envs from what I remember, that's why it's listed as a `provided` dependency in `dependencies.json`. IntelliJ IDEA supports that, I don't know if eclipse does. You could just go into the eclipse dependency list and remove it manually from there though (or temporarily remove it from the dependencies.json file).

**Comment by JamesTompkins** [comment]
I tried a fresh install of the project and used intellij instead. This is the error I am getting: 
https://pastebin.com/zNL2JEnx
[This](https://stackoverflow.com/questions/7076414/java-lang-illegalaccesserror-tried-to-access-method#10538366) references the error, I'm unsure whether its a problem specifically with my machine

**Comment by blay09** [comment]
That's the error I'm talking about. Normally 'provided' should make Extra Utilities not load (it's not required to be installed, it's just in the deps for convenience). Either remove Extra Utilities from the dependencies.json, add `useDepAts` to the `minecraft` block in the `build.gradle` or manually change the Extra Utilties in IntelliJ to Provided.
