### ISSUE TITLE
[1.12.2] errors and weird JEI stuff

### ISSUE THREAD

**Issue by TheSnowyChickens** [blay09/ExCompressum#247]
Hello,

I have 2 little things:
1. I get some errors from the server:
Line 6181: [23:56:36] [Server thread/ERROR] [excompressum]: Entry excompressum:compressed_block could not be generated in HeavySieve because exnihilocreatio:block_dust is not an Ex Nihilo siftable
    Line 6182: [23:56:36] [Server thread/ERROR] [excompressum]: Entry excompressum:compressed_block could not be generated in HeavySieve because exnihilocreatio:block_netherrack_crushed is not an Ex Nihilo siftable
    Line 6183: [23:56:36] [Server thread/ERROR] [excompressum]: Entry excompressum:compressed_block could not be generated in HeavySieve because exnihilocreatio:block_endstone_crushed is not an Ex Nihilo siftable

Is there a possibility to fix it? (I have not the best knowlegde about ex compressum)

2. If I look with JEI into the compressed Gravel sieve entries, I can see 5 JEI pages, but arrived at the last page (5), this side is empty and JEI reset to 4 pages.
![grafik](https://user-images.githubusercontent.com/29357962/43037747-7cf92b8a-8d11-11e8-97b7-9c08897e9935.png)

1.12.2
Forge 2739
ExComp 3.0.22
ExNihiloCreatio 0.2.4

**Comment by blay09** [comment]
The errors are actually warnings being falsely reported as errors, this will be fixed in the next version. Basically the rewards for those mentioned Ex Nihilo blocks have been removed, but they haven't been disabled in the Heavy Sieve, so it still tries to make heavy sieve versions out of those drops. They can generally be ignored if there's no actual issue with the sifting.

The JEI thing was probably a bug in JEI, since Ex Compressum doesn't have control beyond "I provide these recipes", and all the GUI handling is done by JEI. I also didn't have this issue occuring in my test.
