### ISSUE TITLE
The Woooden Crucible's JEI tab is broken

### ISSUE THREAD

**Issue by EmosewaPixel** [blay09/ExCompressum#261]
![image](https://user-images.githubusercontent.com/25333164/47876811-82d03800-de1a-11e8-989a-e63bbb7c558e.png)

**Comment by CritFlaw** [comment]
Any progress on this?

**Comment by SirLyle** [comment]
@blay09 I recently implemented a JEI plugin for creatio's crucible which doesn't have this issue. [PR for it](https://github.com/BloodyMods/ExNihiloCreatio/pull/162)

Basically, you need to filter the ingredients which have no matching stacks (all the blank spaces), can combine the oredict entries (instead of listing them all individually), and paginate the recipes.

**Comment by CritFlaw** [comment]
Please ^
