### ISSUE TITLE
CraftTweaker support

### ISSUE THREAD

**Issue by rlnt** [blay09/ExCompressum#297]
It would be very nice if ExCompressum would get some CraftTweaker support like ExNihilo has.
JSON configs are just nasty for many people and having everything structured in scripts is very nice.

I am still on 1.12.2 and am using Ex Nihilo Creatio which also has CraftTweaker integration.
Sadly you can't inherit recipes from Creatio with the JSONs. I think they are added to late for Ex Compressum to use them.

It would be very nice to have CraftTweaker support.

**Comment by BlayTheNinth** [comment]
Ex Compressum in 1.16+ will use datapacks for configuration, following the path Vanilla has laid out for us. I believe CraftTweaker has some native support for datapacks. ~~Otherwise, someone else would have to make a CraftTweaker addon to support Ex Compressum. I can help by providing the necessary APIs, but the actual implementation is out of scope for me.~~

**Comment by BlayTheNinth** [comment]
1.16+ has CraftTweaker support now, though it still needs to be documented properly: #305
