### ISSUE TITLE
Overhaul bait conditions

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/ExCompressum#301]
Baits aren't very self-explanatory right now, requiring users to guess what blocks they require nearby. This should be changed somehow. Either by displaying the blocks needed, or changing up the requirements.

**Comment by viceverser** [comment]
I very much agree with this idea... I cannot figure out the turtle bait for the life of me... I mean, the biome is like 2 blocks and 2 vegetation???

**Comment by DevilMayCryIfrit** [comment]
same here I'm playing atm6 to the sky and need the turtle seed to finish a quest but i need the turtle bait but can't figure out the spawn conditions please help

**Comment by Jack-McKalling** [comment]
The turtle breeding was 100% broken at some point, because they have unique breeding mechanics. They require a "home beach" coordinate from hatching, and this was missing so they could never breed and make eggs. I think this was patched some time ago but I didn't get to testing it yet. Maybe the spawning is related?

**Comment by BlayTheNinth** [comment]
1.20.1 port shows the blocks it wants in the message
