### ISSUE TITLE
Ex Compressum won't let me load past Post Initialization when launching a modpack with it

### ISSUE THREAD

**Issue by Kevin19281** [blay09/ExCompressum#303]
As the title says I just get stuck on 5/7 Phase 3 Ex Compressum and my Minecraft stops responding
[latest.log](https://github.com/blay09/ExCompressum/files/6012601/latest.log)

**Comment by Kevin19281** [comment]
I'm trying both Skyfactory 3 and Stoneblock 2 but I'm getting the same issues but with different mods

**Comment by BlayTheNinth** [comment]
Can't reproduce and 1.10 is no longer supported

**Comment by abodnar** [comment]
So what is the solution for this since from what I can see, your code relied on http://balyware.com being up and since it no longer is, it's causing the game to not load since the modpack is trying to retrieve something from it. I've confirmed this by looking at my DNS logs and see calls to that domain.

This was working just fine for me till 6/21. So something must of changed.

**Comment by BlayTheNinth** [comment]
Try enabling `skipAutoSieveSkins` in the config or updating the mod / pack you're playing to the latest version.

**Comment by abodnar** [comment]
That fixed it!

Thanks!
