### ISSUE TITLE
Auto Sieve starts spitting out items if results exceed available slots

### ISSUE THREAD

**Issue by ariosos** [blay09/ExCompressum#314]
While the auto-sieve stops when the internal inventory is full, any excess items are still tossed out (as shown by the sulfur in my inventory). The last row (or a buffer-overflow rows) should be used to prevent further sieving until that row is cleared. I'm not sure if the max number of items that can be acquired in one sieve operation is, but the max number of items should not exceed the available free inventory slots.

![image](https://user-images.githubusercontent.com/7917753/112651927-40608900-8e23-11eb-8e7c-c9b48cb34ac1.png)

**Comment by jeremiahwinsley** [comment]
The solution I'd like to see for this is that the sieve would never drop items, and any overflow would just be deleted. I would always prefer to lose some drops vs causing lag if I wasn't extracting fast enough.

**Comment by rlnt** [comment]
You could calculate the output amount before it even processes the input and it would simply stop the machine if the output does not fit.
A bit of user-feedback would be great then. Some people might get confused when this happens. Maybe by making a red cross on the processing bar or create some text above the output field as little warning.

**Comment by SihenZhang** [comment]
Actually, I am playing `ATM 6 - To the Sky` recently. In this modpack, the sieve recipe has **27 output items** at most while the auto sieve only has **20 slots**, so it definitely drops some of the outputs into the world.
I think maybe you can add a `Capacity Upgrade` so that players can increase the slot count of the machine. I know it might be a little bit hard, so a `Void Upgrade` that will make the machine delete the outputs that will be dropped into the world may also be a great idea.

**Comment by zeeoric** [comment]
I am all for a way to increase the internal inventory of the sieve itself.  The point being that it is making more than the internal inventory can hold and it throws it into the world causing lag.  No item should be able to have a higher output than available slots, or your just asking for a disaster and lag.  

The easiest and quickest to fix answer is increase the internal inventory, but I honestly would prefer for it to be some type of upgrade to be honest.

I would go with the quick fix though until the other can be managed, as increasing the internal inventory to say 32 or even 40 slots would be quicker and easier than the upgrade solution and could be done hopefully in a matter of a day or so.

Also being that this issue has been open for so long, I would think a quick fix until a better change could be made would be best at this point, as I have had to disable auto sieve and auto heavy sieve on my server until this can be fixed as it was causing too much lag.

**Comment by BlayTheNinth** [comment]
Instead of upgrades or pre-calculations I will add an internal buffer that can hold as many items as necessary. If something is in the buffer, the machine will be on hold until there is space to clear it out. 

As this is more of a modpack-caused issue (many more drops than normal for a single item), I don't think it warrants designing a whole new upgrade system / GUI.

**Comment by zeeoric** [comment]
This has been ongoing since March, still no fix? I mean wouldn't just increasing the internal storage be a quick fix until you can get the enhancement help you want?

**Comment by Travis9x** [comment]
This is still causing a lot of issues.  Mods like the Thermal series add several more possible outputs for sifting dirt & gravel, which causes the auto-sieve machines to constantly be spitting out items into the world (especially the auto heavy sieve), no matter how fast pipes/connections try to pull items out to make room.  The auto-sieve machines simply need more output slots by default.

**Comment by KlutzyBubbles** [comment]
Possible solution, add a button to the interface to void extra items instead of holding / dropping them, or keep the same functionality with the items either being dropped on the ground like they are now or being placed in a container if there is one present above the machine.

If an internal buffer was added with unlimited space, it could possibly turn into more of a problem as there would be no way to see or know the buffer exists for players and could lead to more questions and confusion rather than it is now.

I have been trying to get this project on my local machine to try some things i had in mind but cant seem to get gradle working, cant find any information on the java version used (sorry to tack on another question) does anyone know the version to use?

**Comment by BlayTheNinth** [comment]
Will be fixed in 1.20.1 port.
